### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by Magissia** [KevinEeckman/SugarSyncLinux#1]
Running SugarSyncLinux.py with Python 3.4 and Tkinter installed doesn't work as expected, maybe there are missing requirements not listed in the requirements list to run this script.

`python3.4 SugarSyncLinux.py`
`Traceback (most recent call last):`
`  File "SugarSyncLinux.py", line 1, in <module>`
`    import sugarsync`
`  File "/home/Trololo/Sources/SugarSyncLinux/sugarsync/__init__.py", line 1, in <module>`
`    import requests`
`ImportError: No module named 'requests'`

**Comment by KevinEeckman** [comment]
You are right, it requires python requests module. I will list it as a dependency.

I'm using Linux Mint and it can be installed through the software manager; the package name is python-requests
